services:
  web:
    image: fastbat/simulador-do-caos:v2
    ports:
    - 8080:3000
    restart: always
    cpuset: "0"
    memswap_limit: 512M
    deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: 512M
    #healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      #interval: 30s
      #timeout: 5s
      #retries: 2
      #start_period: 30s
      #disable: true
